backend:
    name: git-gateway
    branch: main # Branch to update (optional; defaults to master)
media_folder: public
public_folder: /
collections:
    - name: "Content"
      label: "Content"
      files:
          - label: "About"
            name: "about"
            file: "content/pages/About/About.md"
            fields:
                - { label: "Image", name: "about_img", widget: "image" }
                - {
                      label: "Text Paragraph One",
                      name: "about_text1",
                      widget: "string",
                  }
                - {
                      label: "Text Paragraph Two",
                      name: "about_text2",
                      widget: "string",
                  }

          - label: "Footer"
            name: "footer"
            file: "content/pages/Footer/Footer.md"
            fields:
                - { label: "Text", name: "footer_text", widget: "string" }
          - label: "Header"
            name: "header"
            file: "content/pages/Header/Header.md"
            fields:
                - { label: "Logo Image", name: "logo", widget: "image" }
                - { label: "Name", name: "name", widget: "string" }
          - label: "Hero"
            name: "hero"
            file: "content/pages/Hero/Hero.md"
            fields:
                - { label: "Text", name: "hero_title", widget: "string" }
    - label: "Cards"
      name: "cards"
      folder: "content/pages/Cards/"
      create: true
      fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Description", name: "description", widget: "string" }
